* #Configs
** #Company
Adds Company support to emacs
*** Company
Allows-for-code-completion
**** Company-QuickHelp
Pops-up-documentation-for-completion-item
**** Company-Statistics
Remembers-most-used-items-and-favors-them
**** Company-Ycmd
Allows-for-company-to-use-Ycmd
** #Correction
Adds code and spelling correction to emacs
*** Auto-Dictionary
Mode-that-auto-loads-the-right-dictionary-based-on-text-so-far
*** Flycheck
Adds-syntax-checking-for-most-languages
**** Flycheck-pos-tip
Displays-flycheck-error-as-a-tool-tip
*** Flyspell
Adds-spell-check
**** Flyspell-Correct
Adds-method-to-correct-spelling
**** Flyspell-Correct-Helm
Adds-method-to-correct-spelling-using-helm
** #Evil
Adds evil support to emacs
*** Evil
Adds-vim-key-bindings-to-emacs
**** Evil-Anzu
Search-counter-with-evil
**** Evil-Args
Allows-manipulation-of-args-using-evil
**** Evil-Cleverparens
Handles-parentheses-intelligently-with-evil-commands
**** Evil-Commentary
Allows-for-quick-commenting
**** Evil-Ediff
Evil-keys-for-eDiff
**** Evil-Escape
Define-an-escape-sequence-to-escape-from-most-buffers
**** Evil-Exchange
Easily-exchange-two-words
**** Evil-Iedit-State
Adds-Iedit-and-Iedit-insert-states
**** Evil-indent-plus
Adds-commands-for-indenting-w/ evil
**** Evil-Leader
Adds-leader-key-to-evil
**** Evil-Lisp-State
Adds-a-lisp-state-for-evil
**** Evil-Magit
Adds-evil-keys-to-magit
**** Evil-Matchit
Advance-matching-for-%-key
**** Evil-Mc
Multiple-cursors-for-evil
**** Evil-Nerd-Commenter
Adds-easy-commenting-with-evil-mode
**** Evil-Numbers
Allows-manipulation-of-numbers-like-incr-or-decr, with-evil!
**** Evil-Org
Adds-evil-keys-to-org
**** Evil-Search-Highlight-Persist
Allows-for-the-search-highlighting-to-persist
**** Evil-Snipe
Allows-for-advance-character-searching-(f/t-key) for-evil
**** Evil-Surround
Allows-for-easy-changing-of-surrounding-items
**** Evil-Terminal-Cursor-Changer
Allows-the-cursor-to-change-in-terminal-with-evil
**** Evil-Tutor
Adds-evil-mode-tutor
**** Evil-Visual-Mark-Mode
Shows-all-evil-marks-in-buffer
**** Evil-VisualStar
Allows-to-make-visual-selection-the-hit-* to-search
**** Undo-Tree
Vim-undo-tree
** #Fun
Some fun utilities
*** XKCD
XKCD-Browser-in-emacs
** #Git
Git integration with emacs
*** Magit
Emacs-git-interface
*** Git-Timemachine
Allows-you-to-travel-back-through-file-git-history
** #Helm
Adds helm support to emacs
*** Helm
**** Helm-Ag
**** Helm-C-Yasnippet
**** Helm-Company
**** Helm-Descbinds
**** Helm-Flx
**** Helm-Gitignore
**** Helm-Gtags
**** Helm-Make
**** Helm-Mode-Manager
**** Helm-Projectile
**** Helm-Swoop
** #Languages
Adds several languages specific packages to emacs
*** #asm
**** nasm-mode
**** x86-lookup
**** asm-mode
*** #emacs-lisp
**** edebug
**** auto-compile
**** macrostep
**** debug
**** elisp-slime-nav
**** ielm
*** #haskell
**** hindent
**** company-ghci
**** intero
**** ghc
**** cmm-mode
**** haskell-mode
**** hlint-refactor
**** helm-hoogle
**** flycheck-haskell
**** company-ghc
**** company-cabal
*** #go
**** company-go
**** go-rename
**** flycheck-gometalinter
**** go-mode
*** #java
**** company-emacs-eclim
**** eclim
**** company
*** #javascript
**** js-doc
**** json-snatcher
**** json-mode
**** web-beautify
**** livid-mode
**** company-tern
**** js2-refactor
**** skewer-mode
**** tern
**** js2-mode
**** coffee-mode
*** #lua
**** lua-mode
*** #python
**** live-py-mode
**** pyvenv
**** pip-requirements
**** yapfify
**** helm-pydoc
**** py-isort
**** hy-mode
**** company-anaconda
**** pytest
**** anaconda-mode
**** nose
**** python
**** pyenv-mode
**** cython-mode
*** #scheme
**** geiser
** #Org
Adds better org support to emacs
*** Org
Emacs-org-mode
**** Org-Bullets
More-bullet-types-for-org-mode
**** Org-Pomodoro
Adds-basic-time-tracking-software-to-org
** #Text
Adds several text utilities to emacs
*** Aggressive-Indent
Indents-code-while-typing
*** Auto-Yasnippet
Allows-for-temporary-snippets
*** Clean-Aindent-Mode
Auto-indention-that-removes-excess-whitespace-if-needed
*** Expand-Region
Keeps-expanding-region-systematically
*** Indent-Guide
Shows-indention-with-the-pipe-character
*** Lorem-Ipsum
Generates-a-bunch-of-non-sense-text
*** Move-Text
Move-chunks-of-text-around-easily
*** Origami
Text-folding-for-regions
*** Semantic
Allows-for-language-aware-editing
*** Srefactor
Refactoring-tool
*** Ws-Butler
Delete-excess-whitespace-unobtrusively
*** Yasnippet
Allows-for-use-of-snippets-(macro-expansion)
** #Utility
Adds several general utilities to emacs
*** Ag
Interfaces-with-ag, which-is-better-file-searching-than-ack
*** Anzu
Search-match-counter-with-current/total
*** Avy
Adds-links-to-page-for-jumping-like-vimium
**** Ace-Link
Uses-Avy-to-jump-to-links
***** Ace-Jump-Helm-Line
Uses-Ace-Jump-to-jump-to-Helm-lines
*** Desktop
Saves-previous-session
*** eDiff
Easy-diff-between-two-files
*** Eshell
Emacs-shell
**** Esh-help
Adds-several-helpful-functions-to-eShell
*** Exec-Path-From-Shell
Makes-the-ENV-variables-same-as-user-shell
*** Eyebrowse
Emacs-workspace-manager-like-i3
*** Fancy-Battery
Adds-a-battery-indicator-to-emacs
*** Fasd
Commandline-productivity-booster, creates-easy-access-to-directories-already-visited
*** Floobits
Paired-Programming-like-google-docs
*** Fuzzy
Fuzzy-matching, not-sure-if-helm-already-uses-it
*** Hide-Comnt
Allows-user-to-hide-comments
*** Link-Hint
Like-Ace-link-with-some-differences
*** MMM-Mode
Allows-for-multiple-major-modes
*** Multi-Term
Allows-for-multiple-terminal-buffers
*** Open-Junk-File
Opens-a-junk-file-with-the-current-time-and-date-as-filename
*** Pdf-Tools
Tool-for-pdf
*** Persp-Mode
Adds-perspectives-to-emacs
*** PopWin
Removes-popup-system-windows-when-they're-no-long-in-focus
*** Pos-Tip
Tool-Tip-library
*** Projectile
Allows-for-project-handling
*** Restart-Emacs
Restarts-emacs.... duh
*** S
String-manipulation-library-for-emacs
*** Spray
Speed-reading-utility
*** Tiny-Menu
Allows-for-creation-of-mini-menus-bound-to-a-key
*** VirtualEnvWrapper
Allows-for-Virtual-Environments-to-be-created-with-emacs
*** WGrep-ag
Allows-changes-to-grep-buffer
*** Which-key
Tells-you-which-keys-combinations-can-follow-a-key-press
*** Winum
Shows-a-number-for-each-window
*** Ycmd
Allows-for-better-code-completion
*** Zeal-at-point
Offline-documentation-for-languages
*** Zoom-frm
Zoom-font-size
** #Visual
Adds several visual packages to emacs
*** Adaptive-Wrap
Wraps-the-buffer-automatically-and-adapts-the-size-without-changing-buffer
*** All-The-Icons
ADD-ALL-THE-ICONS!
**** All-The-Icons-Dired
ADD-ALL-THE-ICONS! ...to-dired
*** Auto-Highlight-Symbol
*** Centered-Cursor-Mode
Keeps-cursor-centered-in-window
*** Column-Enforce-Mode
Highlights-text-that-goes-beyond-a-column-(80-col-rule)
*** Diff-Hl
Shows-uncommited-changes-in-a-file
*** Golden-Ratio
Keeps-all-windows-akin-to-the-golden-ration
*** Highlight-Numbers
Highlight-numbers-in-code
*** Highlight-Parentheses
Highlights-parentheses-encasing-cursor
*** Highlight-symbol
*** Hl-Todo
Highlights-Todo-statements-and-allows-jumping-to-them
*** Imenu-list
Creates-a-buffer-for-iMenu-(func-defs, etc...)
*** Nlinum-Relative
Displays-relative-line-numbers
*** Rainbow-Delimiters
Colors-delimiters-based-on-depth-level
*** Rainbow-mode
Colorize-color-names
*** Volatile-Highlights
Highlights-last-yank/undo
** #Emacs
Adds several emacs visual utilities
*** Diminish
Allows-hiding-of-minor-modes-in-line-display
*** Powerline
Adds-vim-powerline-in-place-of-mode-bar-on-bottom-of-the-screen
**** Powerline-Evil
Adds-evil-support-to-powerline
*** Smart-Mode-Line
Another-good-status-bar, may-conflict-with-powerline
*** Spaceline
Adds-a-spacemacs-mode-line-theme, probably-conflicts-with-other-mode-line-themes
**** Spaceline-All-The-Icons
ADD-ALL-THE-ICONS! ...to-spaceline
** #Web
Adds a few web packages to emacs
*** Bbdb
Creates-a-complete-address-book-for-people
*** Engine-Mode
Allows-for-searching-of-search-engines
*** Gnus
Reading-email-from-emacs
