export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export TERM="xterm-256color"
export PROMPT='%15<..<%~%# '
export RPROMPT='%t'

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=1000
setopt appendhistory autocd beep extendedglob nomatch notify
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/jack/.zshrc'

autoload -Uz compinit
compinit

export PATH="$PATH:/usr/local/avr/bin"

# Make sure that the output of ls is colorized
alias ls='ls --color=auto'
# Allow for nakai's own stupidity with exiting
alias exi='exit'
alias :exi='exit'

# Set python to python3
alias python='python3'
alias pip='pip3'

# Set to vi key binds
bindkey -v
set editing-mode vi
set show-mode-in-prompt on

# Escape sequence for vi key bindings
bindkey jk vi-cmd-mode
bindkey kj vi-cmd-mode

# Changes the cursor
function zle-line-finish zle-keymap-select () {
	if [ "$TERM" = "xterm-256color" ]; then
		if [ $KEYMAP = vicmd ]; then
			# the command mode for vi
			echo -ne "\e[1 q"
		else
			# the insert mode for vi
			echo -ne "\e[5 q"
		fi
	fi
}

function zle-line-init (){
	zle -K vicmd;
	if [ "$TERM" = "xterm-256color" ]; then
		if [ $KEYMAP = vicmd ]; then
			# the command mode for vi
			echo -ne "\e[1 q"
		else
			# the insert mode for vi
			echo -ne "\e[5 q"
		fi
	fi
}

zle -N zle-keymap-select
zle -N zle-line-init
zle -N zle-line-finish

# Less mode time to switch modes, may cause bugs
export KEYTIMEOUT=10
