#!/bin/bash

amount=${2:0}
case "$1" in
	increase)
		xbacklight -inc $amount%
		;;
	decrease)
		xbacklight -dec $amount%
		;;
	max)
		xbacklight -set 100%
		;;
	min)
		xbacklight -set 1%
		;;
	none)
		xbacklight -set 0%
		;;
	*)
		echo "Usage: $0 {increase|decrease|max|min|none} {amount}"
		exit 2
esac
exit 0
