#!/bin/sh -e

selection=$(hacksaw -f "-i %i -g %g")
sleep 0.1 #wait for picom
if [ -z "$1" ]
then
	shotgun $selection - | xclip -t 'image/png' -selection clipboard
else
	echo $1
	shotgun $selection $1
fi
