#!/bin/bash

DEVICE=$(xinput list | grep "Finger touch" | sed 's/.*id=\([0-9]\+\).*/\1/')

case "$1" in
    disable)
		xinput --disable $DEVICE
        ;;
    enable)
		xinput --enable $DEVICE
        ;;
    *)
        echo "Usage: $0 {enable|disable}"
        exit 2
esac

exit 0