#!/bin/sh

case "$1" in
	increase10)
		pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo +10%
		;;
	decrease10)
		pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo -10%
		;;
	increase1)
		pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo +1%
		;;
	decrease1)
		pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo -1%
		;;
	mute)
		pactl set-sink-mute alsa_output.pci-0000_00_1b.0.analog-stereo on
		;;
	nomute)
		pactl set-sink-mute alsa_output.pci-0000_00_1b.0.analog-stereo off
		;;
	toggle)
		pactl set-sink-mute alsa_output.pci-0000_00_1b.0.analog-stereo toggle
		;;
	*)
        echo "Usage: $0 {increase|decrease|mute|nomute|toggle}"
		exit 2
esac
exit 0
