#!/bin/bash

amount=${2:0}
device=alsa_output.pci-0000_00_1b.0.analog-stereo
case "$1" in
	increase)
		pactl set-sink-volume $device +$amount%
		;;
	decrease)
		pactl set-sink-volume $device -$amount%
		;;
	mute)
		pactl set-sink-mute $device on
		;;
	nomute)
		pactl set-sink-mute $device off
		;;
	toggle)
		pactl set-sink-mute $device toggle
		;;
	*)
        echo "Usage: $0 {increase|decrease|mute|nomute|toggle} {amount}"
		exit 2
esac
exit 0
